### PR TITLE
Ran Without Error

### PR DESCRIPTION
**Pull request by syounkin**
This is the first pull request in which I have successfully run route_analysis.Rmd without error. This pull request also contains some changes to the Makefile and relative paths to subdirectories.

### CODE REVIEW

**Comment by bvarick** [comment]
I had changed the relative paths to the subdirectories so that I could run the route_analysis.Rmd from Rstudio (and work on it line by line). When I open the markdown file in Rstudio, it's working directory is the location that the markdown file is stored (`route_analysis/R`), I can't figure out how to change that, so I changed the relative paths of the subdirectories instead. Then, In order for the make file to work, I changed the knit_root_dir to match. 

Do you have a suggestion for how I can change the working directory of route_analysis.Rmd outside of the make file? The other work around I see is to store route_analysis.Rmd in the route_analysis directory, not route_analysis/R

**Comment by bvarick** [comment]
Or the other solution, is pull the bulk of the script back out into an R script, and have the RMarkdown file call the Rscript.

**Comment by bvarick** [comment]
When merging in your pull request, I merged in a separate change I had made. I'm pretty new at using git, sorry about that. The change I merged in changes the filename of the wisconsin school location dataset. Based on Karl Broman system of not changing the raw data, I changed the name of the file to what it's called from the DPI website in the README.

**Comment by syounkin** [comment]
Does `setwd("~/route_analysis/")` or `setwd("./../")` do the trick?

**Comment by bvarick** [comment]
I figured it out. I just needed to change my settings in RStudio to evaluate with the project as the working directory, not the Rmarkdown file as the working directory.

**Pull request merged**
